title: Charles Grimes Gerrity, Ph.D.
description: Neuroscientist and machine learning engineer specializing in cognitive brain-computer interfaces.
theme: jekyll-theme-minimal # This is a clean, professional theme supported natively by GitHub
logo: /CV_Photo_Zoom.jpg
